### ISSUE TITLE
As a user, I would like to retrieve posts that were created within 5 miles of me so that I can see what people are talking about. 

### ISSUE THREAD

**Issue by ahumay** [CS130-W20/team-A6#8]
## User Story
As a user, I would like to retrieve posts that were created within 5 miles of me so that I can see what people are talking about. 

## Detailed Description
The server gets a request from the user, with the user's location. The request also contains what data the user would like to receive. The server uses these two pieces of information to efficiently return only pertinent data. 

## Acceptance Criteria
The user receives data that is within 5 miles of their location and is the data type that they asked for.

**Comment by dwong777** [comment]
Exposed API on server side to do this so client can query for posts within x miles
